# Model parameters -----------------------------------
model:
  label_cnt: 1
  class: 'ResnetUnet'
  ext:
    encoder_l2_decay: 0.01
    process_channels: 256
# Metric parameters ----------------------------------
metric:
  map_iou:
    thresholds: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
    pred_thresh: 0.5
# Data parameters ------------------------------------
data:
  class: 'ImageDataInput'
  train_file_pattern: ['./tgs/data/train/tfrecord/tgs[0-2][0-9]', './tgs/data/train/tfrecord/tgs[3][0-5]']
  valid_file_pattern: ['./tgs/data/train/tfrecord/tgs[3][6-9]']
  test_file_pattern: ['./tgs/data/test/tfrecord/tgs*']
  shuf_buf: 5000
  parallel_calls: 4
  ext:
    resize_dim: 128
    resize_method: 'pad'
# Base training parameters ---------------------------
batch_size: 20
train_steps: 2000
valid_steps: 40
learning_rate:
  base: 0.001
  cosine_decay:
    steps: 3000
    m_mul: 0.65
    alpha: 0.01
l2_weight_decay: 0.01
l2_normalize:
optimizer:
  adam:
    epsilon: 0.0001
clip_grad_norm:
ema_decay:
log_steps: 10
checkpoint:
  save_seconds: 999999
  keep: 80
  warm_start:
    checkpoint_path: './tgs/training-runs/init/resnet_v1_50.ckpt'
    var_map: './tgs/training-runs/init/resnet_v1_50.json'
    var_init: '.*resnet_v1_50.*'

